config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts
  resources :main

  root 'main#index', as: 'home'

  get 'about' => 'about#aboutme', as: 'about'
  get '/main(/:hello)', to: 'main#index'
  get 'posts/page/(:page(.:format))', to: 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :commentable, polymorphic: true
  validates :body, presence: true, length: {minimum: 3}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 1}
  validates :body, presence: true, length: { minimum: 5}
  has_many :comments, as: :commentable
  has_many :commentators, through: :comments, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_destroy :log_before_destory
  after_destroy :log_after_destory

  has_many :posts
  has_many :comments
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :User
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :Post

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true

  private
  
  def log_before_destroy
    Rails.logger.info "User #{@name} has prepare to delete"
  end
  def log_after_destroy
    Rails.logger.info "User #{@name} has delete"
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
    ###
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    ###
    Rails.logger.info '############'
    Rails.logger.info params.inspect
    Rails.logger.info '############'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :​authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).page(params[:page]).per(3)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :visible)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:comment).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :name, :email, :comment_id, :visible)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/aboutme.html.slim
section.container
  .container.card-body
    h2.card-title
      | Страница блога обо мне
    p.card-text
      | Пара слов обо мне
    p.card-text
      | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    p.card-text
      | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  .links.card-body

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    main.container
      header
        .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-dark.text-white.border-bottom.shadow.p-3.mb-5
          h5.my-0.mr-md-auto.font-weight-bold
            | Ruby on Rails + Bootstrap 4, v.2
          nav.my-2.my-md-2.mr-md-2
            span.btn.btn-light.p-7
              = link_to "На главную", home_path
            span.btn.btn-light.p-7
              = link_to "Обо мне", about_path
            span.btn.btn-light.p-7
              = link_to "Посты", posts_path
      section.yield.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-dark.text-white.border-bottom.shadow.p-3.mb-5
        = yield
      footer.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-dark.text-white.border-bottom.shadow.p-3.mb-5
        p.align-items-cente
          | Rails blog, 2018

app/views/main/index.html.slim
section.container
  .container.card-body
    h2.card-title
      | Главная страница блога
    p.card-text
      | Пара слов о блоге
    p.card-text
      | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  .links.card-body

app/views/posts/_form.html.slim
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    #error_explanation
      h2
        = pluralize(post.errors.count, "error")
        |  prohibited this post from being saved:
      ul
        - post.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .field
    = form.label :visible
    = form.check_box :visible
  .actions
    = form.submit

app/views/posts/_post.html.slim
tr
  td
    = post.title
  td
    = post.body
  td
    = post.user.name
  td
    = post.visible
  td
    = link_to 'Show', post
  td
    = link_to 'Edit', edit_post_path(post)
  td
    = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/edit.html.slim
h1
  | Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|  | 
= link_to 'Back', posts_path

app/views/posts/index.html.slim
p#notice
  = notice
h1
  | Posts
table
  thead
    tr
      th
        | Title
      th
        | Body
      th
        | User
      th
        | Visible
      th[colspan="3"]
  tbody
    - @posts.each do |post|
      = render partial: 'post', collection: @posts
br
= paginate @posts
= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1
  | New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @post.title
p
  strong
    | Body:
  = @post.body
p
  strong
    | Visible:
  = @post.visible
p
  strong
    | Comments:
  table
    - @post.comments.order(:created_at).each do |c|
      tr
        td
          = c.user.name
        td
          = c.body
p.pagination
  = paginate @posts
= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/shared/_header.html.slim
header
 ul
  - if user_signed_in?
  li
  span = t('label.hello') % current_user.name
  li
  = link_to t('label.logout'), destroy_user_session_path, method: :delete
  -else
  li
  = link_to t('label.login'), new_user_session_path
  li
  = link_to t('label.registration'), new_user_registration_path

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :id
    = form.text_field :id
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :email
    = form.text_field :email
  .field
    = form.label :comment_id
    = form.text_field :comment_id
  .field
    = form.label :visible
    = form.check_box :visible
  .actions
    = form.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Users
table
  thead
    tr
      th
        | Id
      th
        | Name
      th
        | Email
      th
        | Comment
      th
        | Visible
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.id
        td
          = user.name
        td
          = user.email
        td
          = user.comment
        td
          = user.visible
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
p
  strong
    | Id:
  = @user.id
p
  strong
    | Name:
  = @user.name
p
  strong
    | Email:
  = @user.email
p
  strong
    | Comment:
  = @user.comment
p
  strong
    | Visible:
  = @user.visible
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path